### ISSUE TITLE
burrito sync files fails if SSH port if specified

### ISSUE THREAD

**Issue by strackoverflow** [trivera/burrito#2]
If an SSH port is defined in the sync.ini config file, the rsync command will fail.

**Comment by macek** [comment]
this is an atrocity!

**Comment by strackoverflow** [comment]
Haha! Forgot you must still get issue notifications for this repo.

**Comment by macek** [comment]
It looks like the script is configured properly to set the `-p` param:
https://github.com/trivera/burrito/blob/master/libraries/cli/cmd/sync.php#L130-L133

```
// port
if ($_=$options['port']) {
    echo "-p {$_} "; 
}
```

Can you paste a output of the command?

Obviously, make sure to replace sensitive information with `<host>` or `<ip>` or whatever.

**Comment by macek** [comment]
You might be able to replace the `if` statement above with the following line:

```
echo sprintf("-p %d ", $_=$options['port'] ? $_ : 22);
```

This has added benefit of explicitly using port 22 when no port is specified

**Comment by strackoverflow** [comment]
Actually doesn't rsync need the port specified in the `rsh` parameter? so `--rsh="ssh"` would be `--rsh="ssh -p22"` to explicitly set the port. Think I'll just need to edit the command string to accommodate for that.

**Comment by macek** [comment]
`_rsync` calls the `_ssh` helper here:
https://github.com/trivera/burrito/blob/master/libraries/cli/cmd/sync.php#L194-L197

```
_ssh(array_merge(
    BurritoConfig::env('sync', 'ssh'),
    array('path'=>$options['remote_dir'])
) //...
```

So that takes care of the ssh port. It only needs to be defined in one place; i.e., the `_ssh` helper

**Comment by macek** [comment]
Actually, this might be a quoting issue! Try changing this part:

```
--rsh="ssh" %s
```

To:

```
--rsh="ssh %s"
```

**Comment by strackoverflow** [comment]
Right, I'm saying that `-p 22` is incorrect syntax for rsync, isn't it? Here's what burrito generates for rsync when the port is specified:

``` bash
rsync  -rvtzp --exclude="backups/*" --exclude="cache/*" --exclude="tmp/*" --exclude="trash/*" --progress --rsh="ssh" -p 22 {user}@{host}:{remote_dir} {local_dir}
```

When it should actually be

``` bash
rsync  -rvtzp --exclude="backups/*" --exclude="cache/*" --exclude="tmp/*" --exclude="trash/*" --progress --rsh="ssh -p22" {user}@{host}:{remote_dir} {local_dir}
```

I just need to rearrange that to put the port parameter in the `--rsh` flag when I get a chance.

**Comment by strackoverflow** [comment]
Haha yes that's what I was trying to say.

**Comment by szsori** [comment]
Thanks Dave, this issue has been bothering me.  ;)

**Comment by triveraguy** [comment]
It's even been bothering me, and I have no clue!

**Comment by macek** [comment]
Haha is anyone having an *actual* issue? I think I authored the syncing script, I could look into it if someone is still relying upon this.

**Comment by triveraguy** [comment]
The only issues we've had are still finding a few legacy sites still using it. ;)  We finally just completed our total burrito exorcism portfolio-wide. :)

**Comment by strackoverflow** [comment]
Haha I remembered @triveraguy telling me burrito was retired recently so I finally felt comfortable closing this 😅

**Comment by triveraguy** [comment]
I don't believe that "retired" was the actual word I used to describe it.  Pretty sure the terminology was that we gave it a "fitting burial." LOL
